#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.material-mod >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.materialmod=/luci-static/material-mod
		set luci.main.mediaurlbase=/luci-static/material-mod
		commit luci
	EOF
fi

exit 0
